import { notFound } from "next/navigation";
import { UserRole } from "@prisma/client";
import { enrollEmployees, setCourseStatus } from "@/actions/courses";
import { retryContent, uploadContent } from "@/actions/content";
import { ActionForm } from "@/components/action-form";
import { db } from "@/lib/db";
import { requireRole } from "@/lib/session";

export default async function CourseAdminPage({ params }: { params: Promise<{ id: string }> }) {
  await requireRole(UserRole.SUPER_ADMIN); const { id } = await params;
  const course = await db.course.findUnique({ where: { id }, include: { companies: { include: { company: true } }, teachers: { include: { user: { include: { employee: true } } } }, contents: { include: { lessons: true }, orderBy: { version: "desc" } }, enrollments: { include: { employee: true } } } });
  if (!course) notFound();
  const employees = await db.employee.findMany({ where: { status: "ACTIVE", companyId: { in: course.companies.map((c) => c.companyId) }, enrollments: { none: { courseId: id } } }, orderBy: { name: "asc" } });
  return <main className="container"><span className="badge">{course.status.replaceAll("_", " ")}</span><h1>{course.title}</h1><p>{course.description}</p><div className="two-col"><section className="card"><h2>Content</h2>{course.contents.map((content) => <div className="card" key={content.id}><strong>Version {content.version}: {content.originalName}</strong><p><span className="badge">{content.processingStatus}</span> {content.isPublished && <span className="badge">LIVE</span>} · {(content.sizeBytes/1048576).toFixed(1)} MB</p>{content.processingError && <p className="error">{content.processingError}</p>}<p>{content.lessons.length} lesson(s) {content.approvedAt ? "· Approved" : ""}</p>{content.processingStatus === "FAILED" && <form action={retryContent}><input type="hidden" name="contentId" value={content.id}/><button className="secondary">Retry processing</button></form>}</div>)}{!course.contents.length && <p>No content uploaded.</p>}<hr/><h3>Upload content</h3><ActionForm action={uploadContent} submitLabel="Upload and queue"><input type="hidden" name="courseId" value={course.id}/><label>PDF, PowerPoint, or MP4<input type="file" name="file" accept=".pdf,.ppt,.pptx,.mp4" required /></label></ActionForm></section>
  <aside className="form"><div className="card"><h2>Course details</h2><p><strong>Teacher:</strong> {course.teachers.map((t) => t.user.employee?.name ?? t.user.email).join(", ")}</p><p><strong>Companies:</strong> {course.companies.map((c) => c.company.name).join(", ")}</p><p><strong>Duration:</strong> {course.durationMinutes} minutes</p><p><strong>Enrolled:</strong> {course.enrollments.length}</p>{course.status === "PENDING_TEACHER_APPROVAL" && <p className="muted">The assigned teacher must approve content before publication.</p>}{course.status === "PUBLISHED" && <form action={setCourseStatus}><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="status" value="ARCHIVED"/><button className="secondary">Archive course</button></form>}</div>
  <div className="card"><h2>Enroll employees</h2>{employees.length ? <form action={enrollEmployees} className="form"><input type="hidden" name="courseId" value={course.id}/><div style={{maxHeight:280,overflow:"auto"}}>{employees.map((employee) => <label className="checkbox" key={employee.id}><input type="checkbox" name="employeeIds" value={employee.id}/>{employee.name} ({employee.employeeCode})</label>)}</div><button>Enroll selected</button></form> : <p>All eligible employees are enrolled.</p>}</div></aside></div></main>;
}
